settings:
  docker:
    parent_image: str
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false



parameters:
    links: 
      - # insert demo data source link here (e.g., public Google Sheet)
    reflections: false
    collection_names:
      - # insert demo collection names 